name: Create a PR from an issue - Outside Collaborators
on:
  issues:
    types: [opened]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'pr-create-issue')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Check if pull request in a fork
        run: |
          python3 -m pip install -r scripts/requirements.txt
          python3 scripts/create-pr-from-issue.py ${{ secrets.GITHUB_TOKEN }} ${{ toJson(github.event.issue) }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Failed GitHub Action Run'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
